# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Verilog/Cmod-A7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_0_0/design_1_ADC_counter_low_HZ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_0_0 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_1_0/design_1_ADC_counter_low_HZ_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_1_0 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_0/design_1_ADC_counter_low_HZ_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_0 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_0 || ORIG_REF_NAME==design_1_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_1/design_1_ADC_counter_low_HZ_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_1 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_1/design_1_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_1 || ORIG_REF_NAME==design_1_axi_gpio_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_2/design_1_ADC_counter_low_HZ_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_2 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_2/design_1_axi_gpio_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_2 || ORIG_REF_NAME==design_1_axi_gpio_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_3/design_1_ADC_counter_low_HZ_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_3 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_3/design_1_axi_gpio_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_3 || ORIG_REF_NAME==design_1_axi_gpio_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_4/design_1_ADC_counter_low_HZ_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_4 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_4/design_1_axi_gpio_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_4 || ORIG_REF_NAME==design_1_axi_gpio_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_5/design_1_ADC_counter_low_HZ_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_5 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_5/design_1_axi_gpio_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_5 || ORIG_REF_NAME==design_1_axi_gpio_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_6/design_1_ADC_counter_low_HZ_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_6 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_6/design_1_axi_gpio_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_6 || ORIG_REF_NAME==design_1_axi_gpio_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_7/design_1_ADC_counter_low_HZ_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_7 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_7/design_1_axi_gpio_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_7 || ORIG_REF_NAME==design_1_axi_gpio_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_8/design_1_ADC_counter_low_HZ_2_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_8 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_8/design_1_axi_gpio_2_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_8 || ORIG_REF_NAME==design_1_axi_gpio_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ADC_counter_low_HZ_2_9/design_1_ADC_counter_low_HZ_2_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ADC_counter_low_HZ_2_9 || ORIG_REF_NAME==design_1_ADC_counter_low_HZ_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_2_9/design_1_axi_gpio_2_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_2_9 || ORIG_REF_NAME==design_1_axi_gpio_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_12_0/design_1_axi_gpio_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_12_0 || ORIG_REF_NAME==design_1_axi_gpio_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_GPIO_Timer_0_0/design_1_GPIO_Timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_GPIO_Timer_0_0 || ORIG_REF_NAME==design_1_GPIO_Timer_0_0} -quiet] -quiet

# XDC: c:/Users/owenm/OneDrive/Documents/programming/Verilog/ADC_interface_low_HZ/ADC_interface_low_HZ.gen/sources_1/bd/design_1/design_1_ooc.xdc
